version: '3'

services:
  ffmpeg-server:
    build: .
    ports:
      - "80:3000"
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ffmpeg_data:
    driver: local 