name: ffmpeg_server_tests
description: Tests for FFmpeg server functionality

environment:
  sdk: ^3.6.2

dependencies:
  http: ^1.3.0
  http_parser: ^4.1.2

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0 